### ISSUE TITLE
PyTorch wrapper incompatible with PyTorch 0.5

### ISSUE THREAD

**Issue by jon-e-barker** [NVIDIA/nvvl#57]
```Traceback (most recent call last):
  File "main.py", line 321, in <module>
    main(parser.parse_args())
  File "main.py", line 198, in main
    for inputs in train_loader:
  File "/home/jbarker/Projects/nvvl/examples/pytorch_superres/dataloading/dataloaders.py", line 72, in __iter__
    return iter(self.loader)
  File "/opt/conda/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/loader.py", line 121, in __iter__
    self.dataset._read_sample(i)
  File "/opt/conda/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/dataset.py", line 274, in _read_sample
    frame, self.sequence_length)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 202, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: int() not supported on cdata 'struct THLongTensor *'```

**Comment by jaredcasper** [comment]
Sounds like PyTorch 0.5 will required a pretty significant rewrite of the wrapper...

https://github.com/pytorch/extension-ffi/issues/19

**Comment by jbohnslav** [comment]
I also got this bug with PyTorch 0.4.1, but only when I was using a sampler.

**Comment by jaredcasper** [comment]
You should be able to use the new "pytorch1.0" wrapper on any pytorch that includes the pybind11 interface.  I'm not sure when they added it, but PyTorch 0.4.1 might include it.
