### ISSUE TITLE
VideoLoader holds still uses GPU after GPU

### ISSUE THREAD

**Issue by JoakimHaurum** [NVIDIA/nvvl#76]
HI,

I am currently using two VideoLoaders, one for loading training data and one for validation data. My outer loop for running through my epochs is shown below, where the get_loader function is based on the one from the Super-res example, wit ha buffer length of 3. I have not touched any of the internals of the VideoLoader or VideoDataset classes, and only adapted the NVVL class to accomendate some choices regarding sampler etc. 

When transitioning between the training and validation loops (again based on the super-res examples), my script breaks with an OOM message (see below). I inserted the sleep after the training loop, and found that before entering the validation loop, the training VideoLoader is still using the GPU (shown in the nvidia-smi logs below). This causes problems when entering the validation loop, as it cannot allocate enough memory. Each of the loops run well on their own, it is when they have to segwey from one to the other problems occur. My intuition would be that when the data loaders have gone through an epoch, they would also no longer utilize the GPU. Is there a way to somehow flush the VideoLoader data from the GPU before transitioning into the next phase of the outer training loop? I have set the validation and training batch sizes so that as much of the GPU is utilized at a time, while if I reduce the batch sizes then I can transition fine, but only end up using ~50% of the total GPU VRAM 

Outer-training loop
```
    print("Initializing dataloader")
    if args.FCN:
        args.val_batchsize = 3
    else:
        args.val_batchsize = 14

    train_loader, train_batches, val_loader, val_batches, sampler = get_loader(args)
    trn_samples_per_epoch = train_batches * args.batchsize
    val_samples_per_epoch = val_batches * args.val_batchsize

    print("Trn Batch size: {}\nTrn batches: {}\nTrn videos: {}\nVal Batch size: {}\nVal batches: {}\nVal videos: {}\nTrn samples per epoch: {}\nVals samples per epoch: {}".format(args.batchsize, train_batches, len(train_loader.files), args.val_batchsize, val_batches,len(val_loader.files), trn_samples_per_epoch, val_samples_per_epoch))
    print('Dataloaders initialized\n')

    for epoch in range(args.start_epoch, args.epochs):
            _start = time.time()
               
            scheduler.step()
            writer.add_scalar('Learning Rate', optimizer.param_groups[0]["lr"], epoch)

            # train for one epoch
            lossT, accT, timeT = train(train_loader, model, criterion, optimizer, epoch, writer, args)
            writer.add_scalar('Loss/Training-Avg', lossT, epoch)
            writer.add_scalar('Accuracy/Training', accT, epoch)
            writer.add_scalar('Time/Training-Avg', timeT, epoch)

            print("Epoch {} training completed: {}".format(epoch, datetime.datetime.now().isoformat()))
            time.sleep(6)

            # evaluate on validation set
            lossV, accV, timeV = validate(val_loader, model, criterion, args)
            writer.add_scalar('Loss/Validation-Avg', lossV, epoch)
            writer.add_scalar('Accuracy/Validation', accV, epoch)
            writer.add_scalar('Time/Validation-Avg', timeV, epoch)
            
            print("Epoch {} validation completed: {}".format(epoch, datetime.datetime.now().isoformat()))

            # remember best acc@1 and save checkpoint
            is_best = accV > best_accV
            best_accV = max(accV, best_accV)
            save_checkpoint({
                'epoch': epoch + 1,
                'arch': args.arch,
                'state_dict': model.state_dict(),
                'best_accV': best_accV,
                'optimizer': optimizer.state_dict(),
            }, is_best, dir=os.path.join(args.output, "weights"))
            _end = time.time()

            print("Epoch {}\n\tTime: {} seconds\n\tTrain Loss: {}\n\tTrain Accuracy: {}\n\tValidation Loss: {}\n\tValidation Accuracy: {}\n".format(epoch, _end-_start, lossT, accT, lossV, accV))
```

OOM Error message:

> Epoch: [0][19/25]	Time 1.192 (1.531)	Data 0.334 (0.290)	Loss 0.4297 (0.6099)	Acc@1 0.933 (0.802)
> 
> Epoch: [0][20/25]	Time 1.191 (1.515)	Data 0.340 (0.292)	Loss 0.6572 (0.6122)	Acc@1 0.644 (0.795)
> 
> Epoch: [0][21/25]	Time 1.202 (1.501)	Data 0.347 (0.295)	Loss 0.5831 (0.6108)	Acc@1 0.733 (0.792)
> 
> Epoch: [0][22/25]	Time 1.197 (1.487)	Data 0.344 (0.297)	Loss 0.4795 (0.6051)	Acc@1 0.844 (0.794)
> 
> Epoch: [0][23/25]	Time 1.192 (1.475)	Data 0.339 (0.299)	Loss 0.4957 (0.6006)	Acc@1 0.822 (0.795)
> 
> Epoch: [0][24/25]	Time 1.199 (1.464)	Data 0.336 (0.300)	Loss 0.4492 (0.5945)	Acc@1 0.867 (0.798)
> 
> Epoch 0 training completed: 2018-10-26T09:33:02.176891
> 
> 
> THCudaCheck FAIL file=/opt/pytorch/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
> Traceback (most recent call last):
>   File "main.py", line 546, in <module>
>     main(parser.parse_args())
>   File "main.py", line 251, in main
>     lossV, accV, timeV = validate(val_loader, model, criterion, args)
>   File "main.py", line 364, in validate
>     output = model(input)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
>     outputs = self.parallel_apply(replicas, inputs, kwargs)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
>     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 68, in parallel_apply
>     raise output
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 44, in _worker
>     output = module(*input, **kwargs)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/root/shared/joakim/raingauge/3DCNNRainGauge/models/C3D.py", line 57, in forward
>     h = self.relu(self.conv1(x))
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 43, in forward
>     return F.threshold(input, self.threshold, self.value, self.inplace)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/functional.py", line 585, in threshold
>     return torch._C._nn.threshold(input, threshold, value)
> RuntimeError: cuda runtime error (2) : out of memory at /opt/pytorch/pytorch/aten/src/THC/generic/THCStorage.cu:58

NVIDIA-SMI logs when training loop ended (loop ended at 11:33:02 and sleeps for 6 seconds):

> Fri Oct 26 11:33:01 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
> | 57%   74C    P2   236W / 280W |  10524MiB / 11169MiB |    100%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 29%   65C    P2   251W / 280W |   8904MiB / 11172MiB |     94%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1122      G   /usr/lib/xorg/Xorg                           168MiB |
> |    0      2473      G   compiz                                        41MiB |
> |    0      3399      C   python                                     10310MiB |
> |    1      3399      C   python                                      8893MiB |
> +-----------------------------------------------------------------------------+
> Fri Oct 26 11:33:03 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
> | 57%   70C    P2    85W / 280W |  10524MiB / 11169MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 30%   61C    P2    77W / 280W |   8904MiB / 11172MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1122      G   /usr/lib/xorg/Xorg                           168MiB |
> |    0      2473      G   compiz                                        41MiB |
> |    0      3399      C   python                                     10310MiB |
> |    1      3399      C   python                                      8893MiB |
> +-----------------------------------------------------------------------------+
> Fri Oct 26 11:33:05 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
> | 57%   68C    P2    65W / 280W |  10524MiB / 11169MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 30%   60C    P2    60W / 280W |   8904MiB / 11172MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1122      G   /usr/lib/xorg/Xorg                           168MiB |
> |    0      2473      G   compiz                                        41MiB |
> |    0      3399      C   python                                     10310MiB |
> |    1      3399      C   python                                      8893MiB |
> +-----------------------------------------------------------------------------+
> Fri Oct 26 11:33:07 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
> | 57%   68C    P2    65W / 280W |  10524MiB / 11169MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 30%   59C    P2    60W / 280W |   8904MiB / 11172MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1122      G   /usr/lib/xorg/Xorg                           168MiB |
> |    0      2473      G   compiz                                        41MiB |
> |    0      3399      C   python                                     10310MiB |
> |    1      3399      C   python                                      8893MiB |
> +-----------------------------------------------------------------------------+
> Fri Oct 26 11:33:09 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
> | 57%   69C    P2    81W / 280W |   9332MiB / 11169MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
> | 30%   65C    P2   263W / 280W |   5656MiB / 11172MiB |    100%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1122      G   /usr/lib/xorg/Xorg                           168MiB |
> |    0      2473      G   compiz                                        41MiB |
> |    0      3399      C   python                                      9118MiB |
> |    1      3399      C   python                                      5645MiB |
> +-----------------------------------------------------------------------------+
>

**Comment by jaredcasper** [comment]
Both NVVL and the Video Codec SDK will allocate some buffers and keep them until it is destroyed, but I agree this seems a bit excessive.  Not sure what is taking all of that memory.  One thing to try would be to delete the VideoLoader at the end of a full epoch before validation.  This should deallocate any memory that it uses.  If that doesn't work then I would guess that there is something else grabbing all of that memory.
