### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by zhaozhengChen** [NVIDIA/nvvl#77]
Hi,
I installed it using `python3 setup.py install` on Centos7 with cuda-8.0.
But I get the following error when I try to import nvvl :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/__init__.py", line 1, in <module>
    from .dataset import VideoDataset,ProcessDesc
  File "/root/anaconda3/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/dataset.py", line 9, in <module>
    from . import lib
  File "/root/anaconda3/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/lib/__init__.py", line 3, in <module>
    from ._lib import lib as _lib, ffi as _ffi
ImportError: /root/anaconda3/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/lib/libnvvl.so: undefined symbol: cuvidGetDecoderCaps

```
Is there anything else I have to install or something that I did not understand correctly?
Thanks for your help.

**Comment by jaredcasper** [comment]
This comes from using a slightly older driver.  You can comment out line 126 to line 157 in `src/detail/CUVideoDecoder.cpp` and it should compile and still function, it just won't check to ensure the video is within the size limits of the hardware decoder.

**Comment by zhaozhengChen** [comment]
@jaredcasper 
Thank you for your response. I commented the lines as mentioned and compile it again. 
Then I import nvvl successfully.
Thank you once again for your time. :)
