### ISSUE TITLE
Invalid codec for NvDecoder

### ISSUE THREAD

**Issue by lliuz** [NVIDIA/nvvl#8]
I have a problem when I test to read video. Is there a problem with my compilation?
```
Invalid codec for NvDecoder
Traceback (most recent call last):
  File "video_test.py", line 16, in <module>
    main()
  File "video_test.py", line 7, in main
    dataset = nvvl.VideoDataset(filenames, 1)
  File "/opt/conda/envs/pytorch-py3/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/dataset.py", line 208, in __init__
    count = lib.nvvl_frame_count(self.loader, str.encode(f));
  File "/opt/conda/envs/pytorch-py3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 198, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: Unhandled codec 13
```

**Comment by jaredcasper** [comment]
What codec is the video encoded with?  Can you post the output of `ffprobe <videofile>`?

**Comment by jaredcasper** [comment]
I'm going to assume that this was due to the video being encoded with something besides h264 or hevc and close this, please reopen if that isn't correct and you're still having problems.
