### ISSUE TITLE
Nvvl for pytorch 1.0

### ISSUE THREAD

**Issue by guillaumevr** [NVIDIA/nvvl#85]
Hello,
Is it possible to have some help to build the package for pytorch 1.0 please?
Thanks in advance

**Comment by jaredcasper** [comment]
I just pushed a new wrapper that should work with pytorch 1.0 (in the pytorch1.0 directory).  If you try it out I'd be interested to hear how it goes as I've only done a bit of testing.

**Comment by guillaumevr** [comment]
thank you very much!
the installation worked fine but when I try to import the nvvl library, I get the following error:
`Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/d/home/miniconda3/envs/pytorch/lib/python3.7/site-packages/nvvl-1.1-py3.7-linux-x86_64.egg/nvvl/__init__.py", line 1, in <module>
    from .dataset import VideoDataset,ProcessDesc
  File "/d/home/miniconda3/envs/pytorch/lib/python3.7/site-packages/nvvl-1.1-py3.7-linux-x86_64.egg/nvvl/dataset.py", line 8, in <module>
    from . import _nvvl
ImportError: /d/home/miniconda3/envs/pytorch/lib/python3.7/site-packages/nvvl-1.1-py3.7-linux-x86_64.egg/nvvl/_nvvl.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN4NVVL11VideoLoader13read_sequenceESsii`

I'm running it on ubuntu 18.04
cuda 10.0.130
gcc 7.3.0

**Comment by guillaumevr** [comment]
I built the last version of pytorch from source and it fixed the error

**Comment by jbohnslav** [comment]
Hello @guillaumevr, could you describe your process for building and installing nvvl with pytorch 1.0 and cuda 10? [I'm having an issue where my system seems to be looking for CUDA9.2 files.](https://github.com/NVIDIA/nvvl/issues/88)

**Comment by xvjiarui** [comment]
I am having the same issue as @guillaumevr. 
The error message is `lib/python3.6/site-packages/nvvl-1.1-py3.6-linux-x86_64.egg/nvvl/_nvvl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4NVVL11VideoLoader13read_sequenceESsii`. 
Is there any way to fix this bug without build pytorch from source?

**Comment by rbrigden** [comment]
I am having the same issue as @xvjiarui and @guillaumevr. Would appreciate a solution that does not require building pytorch from source.

**Comment by jclevesque** [comment]
In my case it was a mismatch between compiler options for `libnvvl.so` and `_nvvl.cpython-36m-x86_64-linux-gnu.so`. The python bindings were compiled using the old c++ strings, which gave the following signature for the read_sequence function: 

`0000000000015e70 T NVVL::VideoLoader::read_sequence(std::string, int, int)` 

The nvvl library itself used the new c++ strings which have a rather more complex signature:

`0000000000016c40 T NVVL::VideoLoader::read_sequence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int)`

Fixed it by forcing nvvl to use the old C++ string, add `add_compile_definitions(_GLIBCXX_USE_CXX11_ABI=0)` somewhere in the main CMakeLists.txt. This doesn't seem to have adverse effects, I am able to run the C examples and extract individual frames in python. Will use the library more and see if it's stable.

**Comment by dseuss** [comment]
I can confirm that @jclevesque's solution works
