### ISSUE TITLE
Can't support vedios of different length and width

### ISSUE THREAD

**Issue by ZongwuYang** [NVIDIA/nvvl#94]
NVVL does not seem to support videos of different lengths and widths. Will it be supported later?

```bash
python benchmark.py --root /home/yzw/mycode/nvvl/pytorch1.0/test/data/mp4 --sleep 0.5 --loader NVVL
Namespace(batchsize=8, crop_size=[-1, -1], fp16=False, frames=3, is_cropped=False, loader='NVVL', root='/home/yzw/mycode/nvvl/pytorch1.0/test/data/mp4', sleep=0.5)

Video size:  1080 x 1920

Traceback (most recent call last):
  File "benchmark.py", line 79, in <module>
    main(parser.parse_args())
  File "benchmark.py", line 36, in main
    loader, batches = get_loader(args)
  File "/home/yzw/mycode/nvvl/pytorch1.0/test/dataloading/dataloaders.py", line 124, in get_loader
    fp16=args.fp16)
  File "/home/yzw/mycode/nvvl/pytorch1.0/test/dataloading/dataloaders.py", line 56, in __init__
    processing=processing)
  File "/home/yzw/.conda/envs/nvvl/lib/python3.6/site-packages/nvvl-1.1-py3.6-linux-x86_64.egg/nvvl/dataset.py", line 215, in __init__
    count = self.loader.frame_count(f);
RuntimeError: File /home/yzw/mycode/nvvl/pytorch1.0/test/data/mp4/mda-igpgrr8ibgr8rjk2-src.shot.10.mp4 is not the same size and codec as previous files. This is not yet supported. (1050x696 instead of 1920x1080 or codec 27 != 27)
```

**Comment by aBlueDragon** [comment]
I also need to deal with videos with different length. However, I see that there is a sequence_length argument which is required for initializing a VideoDataset. And I read the code and find that videos shorter than the given value of sequence_length will simply be ignored. 
Will there be a support for loading videos of different length in the future? Generally in mini-batch training, after loading videos, all videos will be padded to the longest length in the mini-batch. I think this is better than fixing the sequence_length.

**Comment by jbohnslav** [comment]
This is a duplicate of #64
